/*
 * home-api
 *
 * The API for the Home Starter project
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ForecastTemperature :  IEquatable<ForecastTemperature>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ForecastTemperature" /> class.
        /// </summary>
        /// <param name="Low">Low.</param>
        /// <param name="High">High.</param>
        /// <param name="Morning">Morning.</param>
        /// <param name="Day">Day.</param>
        /// <param name="Evening">Evening.</param>
        /// <param name="Night">Night.</param>
        public ForecastTemperature(double? Low = null, double? High = null, double? Morning = null, double? Day = null, double? Evening = null, double? Night = null)
        {
            this.Low = Low;
            this.High = High;
            this.Morning = Morning;
            this.Day = Day;
            this.Evening = Evening;
            this.Night = Night;
            
        }

        /// <summary>
        /// Gets or Sets Low
        /// </summary>
        [DataMember(Name="low")]
        public double? Low { get; set; }

        /// <summary>
        /// Gets or Sets High
        /// </summary>
        [DataMember(Name="high")]
        public double? High { get; set; }

        /// <summary>
        /// Gets or Sets Morning
        /// </summary>
        [DataMember(Name="morning")]
        public double? Morning { get; set; }

        /// <summary>
        /// Gets or Sets Day
        /// </summary>
        [DataMember(Name="day")]
        public double? Day { get; set; }

        /// <summary>
        /// Gets or Sets Evening
        /// </summary>
        [DataMember(Name="evening")]
        public double? Evening { get; set; }

        /// <summary>
        /// Gets or Sets Night
        /// </summary>
        [DataMember(Name="night")]
        public double? Night { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ForecastTemperature {\n");
            sb.Append("  Low: ").Append(Low).Append("\n");
            sb.Append("  High: ").Append(High).Append("\n");
            sb.Append("  Morning: ").Append(Morning).Append("\n");
            sb.Append("  Day: ").Append(Day).Append("\n");
            sb.Append("  Evening: ").Append(Evening).Append("\n");
            sb.Append("  Night: ").Append(Night).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((ForecastTemperature)obj);
        }

        /// <summary>
        /// Returns true if ForecastTemperature instances are equal
        /// </summary>
        /// <param name="other">Instance of ForecastTemperature to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ForecastTemperature other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Low == other.Low ||
                    this.Low != null &&
                    this.Low.Equals(other.Low)
                ) && 
                (
                    this.High == other.High ||
                    this.High != null &&
                    this.High.Equals(other.High)
                ) && 
                (
                    this.Morning == other.Morning ||
                    this.Morning != null &&
                    this.Morning.Equals(other.Morning)
                ) && 
                (
                    this.Day == other.Day ||
                    this.Day != null &&
                    this.Day.Equals(other.Day)
                ) && 
                (
                    this.Evening == other.Evening ||
                    this.Evening != null &&
                    this.Evening.Equals(other.Evening)
                ) && 
                (
                    this.Night == other.Night ||
                    this.Night != null &&
                    this.Night.Equals(other.Night)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Low != null)
                    hash = hash * 59 + this.Low.GetHashCode();
                if (this.High != null)
                    hash = hash * 59 + this.High.GetHashCode();
                if (this.Morning != null)
                    hash = hash * 59 + this.Morning.GetHashCode();
                if (this.Day != null)
                    hash = hash * 59 + this.Day.GetHashCode();
                if (this.Evening != null)
                    hash = hash * 59 + this.Evening.GetHashCode();
                if (this.Night != null)
                    hash = hash * 59 + this.Night.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(ForecastTemperature left, ForecastTemperature right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ForecastTemperature left, ForecastTemperature right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
