/*
 * home-api
 *
 * The API for the Home Starter project
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// a single temperature zone
    /// </summary>
    [DataContract]
    public partial class TemperatureZone :  IEquatable<TemperatureZone>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemperatureZone" /> class.
        /// </summary>
        /// <param name="Id">the unique identifier for the zone (required).</param>
        /// <param name="Name">Name (required).</param>
        /// <param name="InputPosition">InputPosition.</param>
        /// <param name="OutputPosition">OutputPosition.</param>
        /// <param name="Zone">Zone.</param>
        public TemperatureZone(int? Id = null, string Name = null, int? InputPosition = null, int? OutputPosition = null, string Zone = null)
        {
            // to ensure "Id" is required (not null)
            if (Id == null)
            {
                throw new InvalidDataException("Id is a required property for TemperatureZone and cannot be null");
            }
            else
            {
                this.Id = Id;
            }
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for TemperatureZone and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            this.InputPosition = InputPosition;
            this.OutputPosition = OutputPosition;
            this.Zone = Zone;
            
        }

        /// <summary>
        /// the unique identifier for the zone
        /// </summary>
        /// <value>the unique identifier for the zone</value>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets InputPosition
        /// </summary>
        [DataMember(Name="inputPosition")]
        public int? InputPosition { get; set; }

        /// <summary>
        /// Gets or Sets OutputPosition
        /// </summary>
        [DataMember(Name="outputPosition")]
        public int? OutputPosition { get; set; }

        /// <summary>
        /// Gets or Sets Zone
        /// </summary>
        [DataMember(Name="zone")]
        public string Zone { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TemperatureZone {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  InputPosition: ").Append(InputPosition).Append("\n");
            sb.Append("  OutputPosition: ").Append(OutputPosition).Append("\n");
            sb.Append("  Zone: ").Append(Zone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((TemperatureZone)obj);
        }

        /// <summary>
        /// Returns true if TemperatureZone instances are equal
        /// </summary>
        /// <param name="other">Instance of TemperatureZone to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TemperatureZone other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.InputPosition == other.InputPosition ||
                    this.InputPosition != null &&
                    this.InputPosition.Equals(other.InputPosition)
                ) && 
                (
                    this.OutputPosition == other.OutputPosition ||
                    this.OutputPosition != null &&
                    this.OutputPosition.Equals(other.OutputPosition)
                ) && 
                (
                    this.Zone == other.Zone ||
                    this.Zone != null &&
                    this.Zone.Equals(other.Zone)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.InputPosition != null)
                    hash = hash * 59 + this.InputPosition.GetHashCode();
                if (this.OutputPosition != null)
                    hash = hash * 59 + this.OutputPosition.GetHashCode();
                if (this.Zone != null)
                    hash = hash * 59 + this.Zone.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(TemperatureZone left, TemperatureZone right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TemperatureZone left, TemperatureZone right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
