/* 
 * API Cadastro
 *
 * Teste para workflow API-based:   - Restlet gera API e exporta swagger.json   - SwaggerHub importa arquivo e gera server stub   - Instala server stub em docker repo: io.swagger   - Compila em máquina x64 e gera linux-arm: io.swagger   - Docker push josemottalopes/io.swagger   - Na Raspberry Pi, com hostname \"pi\", instala-se o Docker   - Docker run -d josemottalopes/io.swagger   - Retorna à maquina x64 e acessa o pi-server-stub via browser   - http://pi:5000/swagger/ui/index.html    
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CompaniesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CompaniesApiTests
    {
        private CompaniesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CompaniesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CompaniesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CompaniesApi
            //Assert.IsInstanceOfType(typeof(CompaniesApi), instance, "instance is a CompaniesApi");
        }

        
        /// <summary>
        /// Test CompaniesCompanyidDelete
        /// </summary>
        [Test]
        public void CompaniesCompanyidDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string companyid = null;
            //instance.CompaniesCompanyidDelete(companyid);
            
        }
        
        /// <summary>
        /// Test CompaniesCompanyidGet
        /// </summary>
        [Test]
        public void CompaniesCompanyidGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string companyid = null;
            //var response = instance.CompaniesCompanyidGet(companyid);
            //Assert.IsInstanceOf<Company> (response, "response is Company");
        }
        
        /// <summary>
        /// Test CompaniesCompanyidPut
        /// </summary>
        [Test]
        public void CompaniesCompanyidPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string companyid = null;
            //Company body = null;
            //var response = instance.CompaniesCompanyidPut(companyid, body);
            //Assert.IsInstanceOf<Company> (response, "response is Company");
        }
        
        /// <summary>
        /// Test CompaniesGet
        /// </summary>
        [Test]
        public void CompaniesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? size = null;
            //decimal? page = null;
            //string sort = null;
            //string name = null;
            //var response = instance.CompaniesGet(size, page, sort, name);
            //Assert.IsInstanceOf<List<Company>> (response, "response is List<Company>");
        }
        
        /// <summary>
        /// Test CompaniesPost
        /// </summary>
        [Test]
        public void CompaniesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Company body = null;
            //var response = instance.CompaniesPost(body);
            //Assert.IsInstanceOf<Company> (response, "response is Company");
        }
        
    }

}
